### ISSUE TITLE
Add board options to README

### ISSUE THREAD

**Issue by touchgadget** [adafruit/Adafruit_IntelliKeys#2]
It would be helpful to include the correct non-default board options in the README.

```
Board: Adafruit Feather RP2040 USB Host
CPU Speed: 120 MHz
USB Stack: Adafruit TinyUSB
```
After installing this library and its dependencies using the Arduino IDE 1.8.19 library manager, the example code builds without problems. So far an IK has been confirmed to work on a Mac M1 running Ventura 13.4 and an iPad M1 running iPadOS 16.5.

**Comment by hathach** [comment]
thank you for the issue, I have update readme to include instruction for compiling https://github.com/adafruit/Adafruit_IntelliKeys#compiling-from-source
